import Head from 'next/head'
import { use, useState } from 'react'
import Link from 'next/link'

const services = [
    {
        title: "----",
        subTitle: [
            { name: "----" }
        ]
    },
    {
        title: "建設業",
        subTitle: [
            { name: "総合工事業" },
            { name: "職別工事業（設備工事業を除く）" },
            { name: "設備工事業" },
        ]
    },
    {
        title: "製造業",
        subTitle: [
            { name: "食料品製造業" },
            { name: "飲料・たばこ・飼料製造業" },
            { name: "繊維工業" },
            { name: "木材・木製品製造業（家具を除く）" },
            { name: "家具・装備品製造業" },
        ]
    },
    {
        title: "情報通信業",
        subTitle: [
            { name: "通信業" },
            { name: "放送業" },
            { name: "情報サービス業" },
            { name: "インターネット附随サービス業" },
            { name: "映像・音声・文字情報制作業" },
        ]
    }
]
export default function Example() {
    const [service, setService] = useState(services[0]);
    const [subServices, setSubService] = useState(service.subTitle);

    const getSubServices = (title) => {
        const s = services.filter(s => s.title == title);
        setService(s)
        setSubService(s.subTitle);
    }
    return (
        <>
            <Head>
                <title>シミュレーション結果</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className='w-8/12 my-5 mx-auto'>
                <div>
                    <div className="md:grid md:grid-cols-3 md:gap-6">
                        <div className="md:col-span-1">
                            <div className="px-4 sm:px-0">
                                <h3 className="text-lg font-medium leading-6 text-gray-900">シミュレーション結果</h3>
                            </div>
                        </div>
                        
                    </div>
                </div>
            </div>
        </>
    )
}
