import Head from 'next/head'
import { use, useState } from 'react'
import Link from 'next/link'
import { getServices } from '../lib/functions'

export default function Example() {
  const serviceMaster = getServices();

  const [serviceName, setServiceName] = useState("-----");
  const [subServices, setSubServices] = useState(["-----"]);
  const [subServiceName, setSubServiceName] = useState("-----");
  const [aboutTax, setAboutTax] = useState({ cost: 0, income: 0, taxableIncome: 0 })

  const getSubServices = (service) => {
    const selectedService = serviceMaster.filter(s => s.name == service)[0];
    setSubServices(selectedService.subServices);
    setServiceName(service);
  };

  const getAboutTax = () => {
    setAboutTax({ cost: 1, income: 1, taxableIncome: 1 })

  }

  return (
    <>
      <Head>
        <title>状況設定</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='bg-gray-900 w-full h-14'>

      </div>
      <div className='w-2/4 my-4 mx-auto'>
        <div className='formWrap'>
          <div className="px-4 sm:px-0 flex justify-center items-start flex-col">
            <h3 className="text-lg font-medium leading-6 text-gray-900 tracking-wide">シミレーション結果</h3>
          </div>
        </div>
        <div className='summaryWrap'>

        </div>
      </div>
    </>
  )
}