import Head from 'next/head'
import { use, useState } from 'react'
import Link from 'next/link'
import { getServices } from '../lib/functions'

export default function Example() {
  const serviceMaster = getServices();

  const [serviceName, setServiceName] = useState("-----");
  const [subServices, setSubServices] = useState(["-----"]);
  const [subServiceName, setSubServiceName] = useState("-----");
  const [aboutTax, setAboutTax] = useState({ cost: 0, income: 0, taxableIncome: 0 })

  const getSubServices = (service) => {
    const selectedService = serviceMaster.filter(s => s.name == service)[0];
    setSubServices(selectedService.subServices);
    setServiceName(service);
  };

  const getAboutTax = () => {
    setAboutTax({ cost: 1, income: 1, taxableIncome: 1 })

  }

  return (
    <>
      <Head>
        <title>状況設定</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='bg-gray-900 w-full h-14'>

      </div>
      <div className='w-2/4 my-4 mx-auto'>
        <div className='formWrap'>
          <div className="px-4 sm:px-0 flex justify-center items-start flex-col">
            <h3 className="text-lg font-medium leading-6 text-gray-900 tracking-wide">状況設定</h3>
          </div>

          <div className="shadow">
            <div className='px-6 py-3 my-4'>
              <div className='my-4 flex items-center justify-center w-full gap-x-1.5'>
                <div className="flex-1">
                  <label htmlFor="country" className="block text-sm font-medium text-gray-700">
                    事業所の位置
                  </label>
                  <select
                    id="country"
                    name="country"
                    autoComplete="country-name"
                    className="mt-1 block w-full rounded-md border border-gray-300 bg-white py-2 px-3 shadow-sm focus:border-indigo-500 focus:outline-none focus:ring-indigo-500 sm:text-sm"
                  >
                    <option>東京23区</option>
                    <option>その他</option>
                  </select>
                </div>
                <div className="flex-1">
                  <label htmlFor="country" className="block text-sm font-medium text-gray-700">
                    従業員の有無
                  </label>
                  <select
                    id="country"
                    name="country"
                    autoComplete="country-name"
                    className="mt-1 block w-full rounded-md border border-gray-300 bg-white py-2 px-3 shadow-sm focus:border-indigo-500 focus:outline-none focus:ring-indigo-500 sm:text-sm"
                  >
                    <option>雇ってる</option>
                    <option>雇ってない</option>
                  </select>
                </div>
              </div>

              <div className='my-4 flex items-center justify-center w-full gap-x-1.5'>
                <div className="flex-1">
                  <label htmlFor="country" className="block text-sm font-medium text-gray-700">
                    従業員数
                  </label>
                  <select
                    id="country"
                    name="country"
                    autoComplete="country-name"
                    className="mt-1 block w-full rounded-md border border-gray-300 bg-white py-2 px-3 shadow-sm focus:border-indigo-500 focus:outline-none focus:ring-indigo-500 sm:text-sm"
                  >
                    <option>50人以下</option>
                    <option>50人超</option>
                  </select>
                </div>
                <div className="flex-1">
                  <label htmlFor="country" className="block text-sm font-medium text-gray-700">
                    青色専従者
                  </label>
                  <select
                    id="country"
                    name="country"
                    autoComplete="country-name"
                    className="mt-1 block w-full rounded-md border border-gray-300 bg-white py-2 px-3 shadow-sm focus:border-indigo-500 focus:outline-none focus:ring-indigo-500 sm:text-sm"
                  >
                    <option>有</option>
                    <option>無</option>
                  </select>
                </div>
              </div>

              <div className='my-4 flex items-center justify-center w-full gap-x-1.5'>
                <div className="flex-1">
                  <label htmlFor="country" className="block text-sm font-medium text-gray-700">
                    扶養者①
                  </label>
                  <select
                    id="country"
                    name="country"
                    autoComplete="country-name"
                    className="mt-1 block w-full rounded-md border border-gray-300 bg-white py-2 px-3 shadow-sm focus:border-indigo-500 focus:outline-none focus:ring-indigo-500 sm:text-sm"
                  >
                    <option>高校生</option>
                    <option>大学生</option>
                    <option>老人扶養親族</option>
                    <option>同居老人扶養親族</option>
                    <option>無</option>
                  </select>
                </div>
                <div className="flex-1">
                  <label htmlFor="country" className="block text-sm font-medium text-gray-700">
                    扶養者②
                  </label>
                  <select
                    id="country"
                    name="country"
                    autoComplete="country-name"
                    className="mt-1 block w-full rounded-md border border-gray-300 bg-white py-2 px-3 shadow-sm focus:border-indigo-500 focus:outline-none focus:ring-indigo-500 sm:text-sm"
                  >
                    <option>高校生</option>
                    <option>大学生</option>
                    <option>老人扶養親族</option>
                    <option>同居老人扶養親族</option>
                    <option>無</option>
                  </select>
                </div>
              </div>

              <div className='my-4 flex items-center justify-center w-full gap-x-1.5'>
                <div className="flex-1">
                  <label htmlFor="country" className="block text-sm font-medium text-gray-700">
                    健康保険の加入
                  </label>
                  <select
                    id="country"
                    name="country"
                    autoComplete="country-name"
                    className="mt-1 block w-full rounded-md border border-gray-300 bg-white py-2 px-3 shadow-sm focus:border-indigo-500 focus:outline-none focus:ring-indigo-500 sm:text-sm"
                  >
                    <option>有</option>
                    <option>無</option>
                  </select>
                </div>
                <div className="flex-1">
                <label htmlFor="country" className="block text-sm font-medium text-gray-700">
                  事業主年齢
                </label>
                <select
                  id="country"
                  name="country"
                  autoComplete="country-name"
                  className="mt-1 block w-full rounded-md border border-gray-300 bg-white py-2 px-3 shadow-sm focus:border-indigo-500 focus:outline-none focus:ring-indigo-500 sm:text-sm"
                >
                  <option>40歳未満</option>
                  <option>40歳以上</option>
                </select>
                </div>
              </div>

              <div className='my-4 flex items-center justify-center w-full gap-x-1.5'>
                <div className="flex-1">
                  <label htmlFor="country" className="block text-sm font-medium text-gray-700">
                    青色申告の有無
                  </label>
                  <select
                    id="country"
                    name="country"
                    autoComplete="country-name"
                    className="mt-1 block w-full rounded-md border border-gray-300 bg-white py-2 px-3 shadow-sm focus:border-indigo-500 focus:outline-none focus:ring-indigo-500 sm:text-sm"
                  >
                    <option>有</option>
                    <option>無</option>
                  </select>
                </div>
                <div className="flex-1">
                  <label htmlFor="country" className="block text-sm font-medium text-gray-700">
                    電子申告の有無
                  </label>
                  <select
                    id="country"
                    name="country"
                    autoComplete="country-name"
                    className="mt-1 block w-full rounded-md border border-gray-300 bg-white py-2 px-3 shadow-sm focus:border-indigo-500 focus:outline-none focus:ring-indigo-500 sm:text-sm"
                  >
                    <option>40歳未満</option>
                    <option>40歳以上</option>
                  </select>
                </div>
              </div>

              <div className='my-4 flex items-center justify-center w-full gap-x-1.5'>
                <div className="flex-1">
                  <label htmlFor="country" className="block text-sm font-medium text-gray-700">
                    配偶者
                  </label>
                  <select
                    id="country"
                    name="country"
                    autoComplete="country-name"
                    className="mt-1 block w-full rounded-md border border-gray-300 bg-white py-2 px-3 shadow-sm focus:border-indigo-500 focus:outline-none focus:ring-indigo-500 sm:text-sm"
                  >
                    <option>有</option>
                    <option>無</option>
                  </select>
                </div>
                <div className="flex-1">
                  <label htmlFor="country" className="block text-sm font-medium text-gray-700">
                    概算の年額医療費
                  </label>
                  <input
                    type="text"
                    name="first-name"
                    id="first-name"
                    autoComplete="given-name"
                    className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
                  />
                </div>
              </div>
            </div>
            <div className="bg-gray-50 px-4 py-3 text-right">
              <Link
                href="/page3"
                type="submit"
                className="inline-flex justify-center rounded-md border border-transparent bg-gray-800 py-2 px-4 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2"
              >
                次へ
              </Link>
            </div>
          </div>
        </div>
        <div className='summaryWrap'>

        </div>
      </div>
    </>
  )
}